### ISSUE TITLE
Spring Cloud Zuul上传中文乱码

### ISSUE THREAD

**Issue by tinyking** [tinyking/growth#1]
```yaml
zuul:
  servlet-path: /

---
spring:
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
```
